# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f319877f53bef4d451b0143a57fa90ecdccfce1b0730b1523c67c88858a5a0ea20f19b8e0ff08b9eb1eaa323d4815a05965fb82da3b4607f27994b99530d5e

test:
  secret_key_base: d8aea01817551f7ba90019ca0e7377aa4ca8b5ad2bbeb70a0c304dc1b3eb249e2c03c81845e04ebf074bdb57358b3d3f6a075bd155549824816cf0a26aaf0326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
